---
- name: SELinux | Modify the configuration file
  become: true
  ansible.builtin.template: 
    src=config.j2 
    dest=/etc/selinux/config
- name: SELinux | Close selinux
  become: true
  ansible.builtin.shell: 
    cmd: setenforce 0
