version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: postgres_1
    environment:
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "password1"
      POSTGRES_DB: "user1"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./backup:/backup
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
