version: "3.9"
services:
  db:
    image: mysql:8
    container_name: mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: "password1"
    volumes:
      - ./test_data:/backup
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
