---
proxy:
  hosts:
    proxy-nginx:
      ansible_host: akulovnetology.ru
      ansible_user: centos
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
db01:
  hosts:
    mysql-master:
      ansible_host: db01.akulovnetology.ru
      ansible_user: centos
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'
db02:
  hosts:
    mysql-slave:
      ansible_host: db02.akulovnetology.ru
      ansible_user: centos
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'
app:
  hosts:
    wp-server:
      ansible_host: app.akulovnetology.ru
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'
gitlab-ce:
  hosts:
    gitlab-server:
      ansible_host: gitlab.akulovnetology.ru
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'
gitlab-run:
  hosts:
    gitlab-runner:
      ansible_host: runner.akulovnetology.ru
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'
monitoring:
  hosts:
    monitoring-server:
      ansible_host: monitoring.akulovnetology.ru
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "/home/akula/.ssh/id_rsa.pub"
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@akulovnetology.ru"'