---
# Config resourse monitoring
- name: Prometheus | Config resourse monitoring
  become: true
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
  notify: restart prometheus
# Config systemd service for Prometheus
- name: Prometheus | Config and start service
  become: true
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  notify: restart prometheus
# Config alert rules
- name: Prometheus | Config alert rules
  become: true
  ansible.builtin.template:
    src: alert_rules.yml
    dest: /etc/prometheus/alert_rules.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0644
  notify: restart prometheus
