---
- name: MySQL | Download MySQL Community Repo
  ansible.builtin.get_url:
    url: "http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm"
    dest: /tmp
- name: MySQL | Install MySQL Community Repo
  become: true
  ansible.builtin.shell:
    cmd: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm
  ignore_errors: true
- name: MySQL | Install MySQL Server
  become: true
  ansible.builtin.yum:
    name: mysql-server
    state: present
- name: MySQL | Install MySQL Client
  become: true
  ansible.builtin.yum:
    name: mysql
    state: present
- name: MySQL | Install MySQL-python
  become: true
  ansible.builtin.yum:
    name: MySQL-python
    state: present
- name: MySQL | Start MySQL Server and enable it
  become: true
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
