---
- name: MySQL | Install packages
  ansible.builtin.include_tasks:
    file: install_mysql.yml
- name: SELinux | Close
  ansible.builtin.include_tasks:
    file: selinux_close.yml
- name: MySQL | Root user password
  ansible.builtin.include_tasks:
    file: root_user_master.yml
- name: MySQL | Config master
  ansible.builtin.include_tasks:
    file: config_master.yml
