---
- name: Alertmanager | Create the alertmanager group
  become: true
  ansible.builtin.group:
    name: "{{ alertmanager_user }}"
    state: present
    system: true
- name: Alertmanager| Create the alertmanager user
  become: true
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    groups: "{{ alertmanager_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
- name: Alertmanager | Get bin
  become: true
  ansible.builtin.unarchive:
    src: "{{ alertmanager_install_url }}"
    dest: /usr/local/bin/
    remote_src: yes
- name: Alertmanager | Set ownership
  become: true
  ansible.builtin.file:
    path: "{{ alertmanager_bin_dir }}"
    state: directory
    recurse: yes
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
