global:
  scrape_interval:  5s
rule_files:
  - "alert_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['proxy.akulovnetology.ru:9101', 'db01.akulovnetology.ru:9101', 'db02.akulovnetology.ru:9101', 'app.akulovnetology.ru:9101', 'gitlab.akulovnetology.ru:9101', 'runner.akulovnetology.ru:9101', 'monitoring.akulovnetology.ru:9101']
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
