---
- name: restart apache service
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted
- name: reload apache service
  become: true
  ansible.builtin.service:
    name: apache2
    state: reloaded
