---
- name: Node Exporter | Config and start service
  become: true
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
  notify: restart node_exporter
